import { User, Medication, DosageScheduleItem, AdherenceStats } from '@/types';

export const mockUser: User = {
  id: 'usr_01',
  email: 'nguyenvana@medisafe.vn',
  fullName: 'Nguyễn Văn A',
  avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150',
  heightCm: 172,
  weightKg: 68,
  allergies: ['Penicillin', 'Aspirin'],
  emergencyContactName: 'Nguyễn Thị B (Vợ)',
  emergencyContactPhone: '0901234567',
  createdAt: '2026-01-15T08:00:00Z',
};

export const initialMockMedications: Medication[] = [
  {
    id: 'med_01',
    userId: 'usr_01',
    name: 'Amoxicillin',
    description: 'Kháng sinh điều trị nhiễm khuẩn hô hấp',
    dosage: 500,
    unit: 'mg',
    shape: 'capsule',
    color: 'blue',
    stockQuantity: 24,
    lowStockThreshold: 5,
    frequencyTimesPerDay: 2,
    reminderTimes: ['08:00', '20:00'],
    startDate: '2026-07-25',
    endDate: '2026-08-05',
    instructions: 'Uống sau bữa ăn 30 phút với nhiều nước',
    createdAt: '2026-07-25T08:00:00Z',
    updatedAt: '2026-07-25T08:00:00Z',
  },
  {
    id: 'med_02',
    userId: 'usr_01',
    name: 'Paracetamol',
    description: 'Thuốc hạ sốt và giảm đau nhẹ đến vừa',
    dosage: 650,
    unit: 'mg',
    shape: 'round',
    color: 'white',
    stockQuantity: 4, // Low inventory alert trigger!
    lowStockThreshold: 10,
    frequencyTimesPerDay: 3,
    reminderTimes: ['08:00', '13:00', '19:00'],
    startDate: '2026-07-20',
    instructions: 'Uống khi bị đau hoặc sốt trên 38.5°C',
    createdAt: '2026-07-20T08:00:00Z',
    updatedAt: '2026-07-20T08:00:00Z',
  },
  {
    id: 'med_03',
    userId: 'usr_01',
    name: 'Omega-3 Fish Oil',
    description: 'Bổ sung axit béo hỗ trợ tim mạch và trí nhớ',
    dosage: 1000,
    unit: 'mg',
    shape: 'oval',
    color: 'yellow',
    stockQuantity: 45,
    lowStockThreshold: 10,
    frequencyTimesPerDay: 1,
    reminderTimes: ['07:30'],
    startDate: '2026-01-01',
    instructions: 'Uống cùng với bữa ăn sáng',
    createdAt: '2026-01-01T08:00:00Z',
    updatedAt: '2026-01-01T08:00:00Z',
  },
  {
    id: 'med_04',
    userId: 'usr_01',
    name: 'Vitamin C Sủi',
    description: 'Tăng cường sức đề kháng',
    dosage: 1000,
    unit: 'mg',
    shape: 'liquid',
    color: 'orange',
    stockQuantity: 18,
    lowStockThreshold: 5,
    frequencyTimesPerDay: 1,
    reminderTimes: ['09:00'],
    startDate: '2026-07-01',
    instructions: 'Hòa tan vào 200ml nước đun sôi để nguội',
    createdAt: '2026-07-01T08:00:00Z',
    updatedAt: '2026-07-01T08:00:00Z',
  },
];

export const getInitialSchedule = (dateStr: string): DosageScheduleItem[] => [
  {
    id: `sch_${dateStr}_01`,
    medicationId: 'med_03',
    medicationName: 'Omega-3 Fish Oil',
    dosage: 1000,
    unit: 'mg',
    shape: 'oval',
    color: 'yellow',
    scheduledTime: '07:30',
    scheduledDate: dateStr,
    status: 'taken',
    takenAt: `${dateStr}T07:35:00Z`,
    notes: 'Đã uống cùng bữa sáng',
  },
  {
    id: `sch_${dateStr}_02`,
    medicationId: 'med_01',
    medicationName: 'Amoxicillin',
    dosage: 500,
    unit: 'mg',
    shape: 'capsule',
    color: 'blue',
    scheduledTime: '08:00',
    scheduledDate: dateStr,
    status: 'taken',
    takenAt: `${dateStr}T08:10:00Z`,
  },
  {
    id: `sch_${dateStr}_03`,
    medicationId: 'med_04',
    medicationName: 'Vitamin C Sủi',
    dosage: 1000,
    unit: 'mg',
    shape: 'liquid',
    color: 'orange',
    scheduledTime: '09:00',
    scheduledDate: dateStr,
    status: 'taken',
    takenAt: `${dateStr}T09:05:00Z`,
  },
  {
    id: `sch_${dateStr}_04`,
    medicationId: 'med_02',
    medicationName: 'Paracetamol',
    dosage: 650,
    unit: 'mg',
    shape: 'round',
    color: 'white',
    scheduledTime: '13:00',
    scheduledDate: dateStr,
    status: 'pending',
  },
  {
    id: `sch_${dateStr}_05`,
    medicationId: 'med_01',
    medicationName: 'Amoxicillin',
    dosage: 500,
    unit: 'mg',
    shape: 'capsule',
    color: 'blue',
    scheduledTime: '20:00',
    scheduledDate: dateStr,
    status: 'pending',
  },
];

export const mockAdherenceStats: AdherenceStats = {
  adherenceRate: 88,
  streakDays: 14,
  totalScheduled: 28,
  totalTaken: 24,
  totalSkipped: 2,
  totalPending: 2,
  weeklyTrend: [
    { day: 'Thứ 2', taken: 4, skipped: 0, scheduled: 4 },
    { day: 'Thứ 3', taken: 3, skipped: 1, scheduled: 4 },
    { day: 'Thứ 4', taken: 4, skipped: 0, scheduled: 4 },
    { day: 'Thứ 5', taken: 4, skipped: 0, scheduled: 4 },
    { day: 'Thứ 6', taken: 3, skipped: 1, scheduled: 4 },
    { day: 'Thứ 7', taken: 3, skipped: 0, scheduled: 4 },
    { day: 'Chủ Nhật', taken: 3, skipped: 0, scheduled: 4 },
  ],
};

export const initialMockAppointments = [
  {
    id: 'apt_01',
    doctorName: 'BS. CKII Nguyễn Thanh Sơn',
    specialty: 'Khoa Tim mạch',
    clinicName: 'Bệnh viện Đa khoa Tâm Anh',
    address: '108 Hoàng Như Tiếp, Long Biên, Hà Nội',
    appointmentDate: '2026-08-05',
    appointmentTime: '09:30',
    status: 'upcoming' as const,
    notes: 'Khám định kỳ huyết áp & tái kê đơn thuốc',
    reminderMinutesBefore: 60,
  },
  {
    id: 'apt_02',
    doctorName: 'BS. CKI Trần Minh Phương',
    specialty: 'Khoa Nội tiết',
    clinicName: 'Bệnh viện Bạch Mai',
    address: '78 Giải Phóng, Đống Đa, Hà Nội',
    appointmentDate: '2026-08-12',
    appointmentTime: '14:00',
    status: 'upcoming' as const,
    notes: 'Xét nghiệm chỉ số đường huyết định kỳ 3 tháng',
    reminderMinutesBefore: 120,
  },
  {
    id: 'apt_03',
    doctorName: 'BS. Lê Hoài Nam',
    specialty: 'Khoa Tai Mũi Họng',
    clinicName: 'Phòng khám Đa khoa Quốc tế',
    address: '45 Lý Thường Kiệt, Hoàn Kiếm, Hà Nội',
    appointmentDate: '2026-07-15',
    appointmentTime: '10:00',
    status: 'completed' as const,
    notes: 'Đã kiểm tra viêm họng cấp - Cho đơn Amoxicillin 7 ngày',
  },
];

export const initialMockNotifications = [
  {
    id: 'notif_01',
    title: 'Nhắc nhở uống thuốc',
    message: 'Đã đến giờ uống 1 viên Paracetamol (650mg) lúc 13:00.',
    type: 'reminder' as const,
    isRead: false,
    createdAt: '2026-07-31T13:00:00Z',
    linkUrl: '/schedule',
  },
  {
    id: 'notif_02',
    title: 'Cảnh báo tồn kho thấp!',
    message: 'Thuốc Paracetamol hiện chỉ còn 4 viên (dưới ngưỡng 10 viên). Hãy bổ sung sớm.',
    type: 'warning' as const,
    isRead: false,
    createdAt: '2026-07-31T09:15:00Z',
    linkUrl: '/medications',
  },
  {
    id: 'notif_03',
    title: 'Lịch hẹn khám sắp tới',
    message: 'Bạn có lịch hẹn với BS. Nguyễn Thanh Sơn vào ngày 05/08/2026 lúc 09:30.',
    type: 'appointment' as const,
    isRead: true,
    createdAt: '2026-07-30T16:00:00Z',
    linkUrl: '/appointments',
  },
  {
    id: 'notif_04',
    title: 'Báo cáo tuần hoàn thành',
    message: 'Tỷ lệ tuân thủ uống thuốc tuần qua của bạn đạt 88%. Giữ vững phong độ nhé!',
    type: 'system' as const,
    isRead: true,
    createdAt: '2026-07-28T08:00:00Z',
    linkUrl: '/statistics',
  },
];

export const initialMockVitals = [
  {
    id: 'vit_01',
    systolic: 122,
    diastolic: 80,
    heartRate: 72,
    bloodGlucose: 105,
    recordedAt: '2026-07-31T07:30:00Z',
    status: 'normal' as const,
    notes: 'Đo sau khi ngủ dậy 15 phút',
  },
  {
    id: 'vit_02',
    systolic: 125,
    diastolic: 82,
    heartRate: 75,
    bloodGlucose: 110,
    recordedAt: '2026-07-30T07:30:00Z',
    status: 'normal' as const,
  },
  {
    id: 'vit_03',
    systolic: 132,
    diastolic: 85,
    heartRate: 78,
    bloodGlucose: 118,
    recordedAt: '2026-07-29T07:30:00Z',
    status: 'elevated' as const,
    notes: 'Hơi mệt sau khi chạy bộ',
  },
  {
    id: 'vit_04',
    systolic: 120,
    diastolic: 78,
    heartRate: 70,
    bloodGlucose: 98,
    recordedAt: '2026-07-28T07:30:00Z',
    status: 'normal' as const,
  },
];
